apiVersion: v1
kind: Service
metadata:
  name: spark-driver
spec:
  selector:
    app: spark-driver
  ports:
  - name: dataPort
    protocol: TCP
    port: 9999
    targetPort: 9999
  clusterIP: None
